apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafdrop
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafdrop
  template:
    metadata:
      labels:
        app: kafdrop
    spec:
      containers:
      - name: kafdrop
        image: obsidiandynamics/kafdrop:latest
        ports:
        - containerPort: 9000
        resources:
          limits:
            cpu: "250m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        env:
        - name: KAFKA_BROKERCONNECT
          value: "10.43.246.98:9092"
        - name: SERVER_SERVLET_CONTEXT_PATH # Thêm dòng này để fix giao diện
          value: "/kafdrop"
---
apiVersion: v1
kind: Service
metadata:
  name: kafdrop
  namespace: kafka
spec:
  selector:
    app: kafdrop
  ports:
    - port: 9000
      targetPort: 9000