version: "3.9"

services:
  web-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-gateway
    restart: always
    ports:
      - "8090:8090"
    environment:
      APP_NAME: web-gateway
      APP_PORT: 8090
      APP_ENV: development

      ORDER_SERVICE_URL: http://order-service:8081/api/v1
      INVENTORY_SERVICE_URL: http://inventory-api:8082/api/v1
      PAYMENT_SERVICE_URL: http://payment-api:8083/api/v1
      NOTIFICATION_SERVICE_URL: http://notification-api:8084/api/v1
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    external: true