apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: inventory-consumer-scaler
  namespace: default
spec:
  scaleTargetRef:
    name: inventory-consumer
  pollingInterval: 15
  cooldownPeriod: 180
  minReplicaCount: 1
  maxReplicaCount: 8
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: kafka-svc.kafka.svc.cluster.local:9092
      consumerGroup: inventory-service-group
      topic: order.created
      lagThreshold: "80"
      activationLagThreshold: "20"
      offsetResetPolicy: latest
      allowIdleConsumers: "false"
      scaleToZeroOnInvalidOffset: "false"
      excludePersistentLag: "false"
      limitToPartitionsWithLag: "false"
      ensureEvenDistributionOfPartitions: "true"

---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: payment-consumer-scaler
  namespace: default
spec:
  scaleTargetRef:
    name: payment-consumer
  pollingInterval: 15
  cooldownPeriod: 180
  minReplicaCount: 1
  maxReplicaCount: 8
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: kafka-svc.kafka.svc.cluster.local:9092
      consumerGroup: payment-service-group
      topic: inventory.reserved
      lagThreshold: "80"
      activationLagThreshold: "20"
      offsetResetPolicy: latest
      allowIdleConsumers: "false"
      scaleToZeroOnInvalidOffset: "false"
      excludePersistentLag: "false"
      limitToPartitionsWithLag: "false"
      ensureEvenDistributionOfPartitions: "true"

---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: notification-consumer-scaler
  namespace: default
spec:
  scaleTargetRef:
    name: notification-consumer
  pollingInterval: 15
  cooldownPeriod: 180
  minReplicaCount: 1
  maxReplicaCount: 8
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: kafka-svc.kafka.svc.cluster.local:9092
      consumerGroup: notification-service-group
      topic: payment.completed
      lagThreshold: "80"
      activationLagThreshold: "20"
      offsetResetPolicy: latest
      allowIdleConsumers: "false"
      scaleToZeroOnInvalidOffset: "false"
      excludePersistentLag: "false"
      limitToPartitionsWithLag: "false"
      ensureEvenDistributionOfPartitions: "true"
  - type: kafka
    metadata:
      bootstrapServers: kafka-svc.kafka.svc.cluster.local:9092
      consumerGroup: notification-service-group
      topic: payment.failed
      lagThreshold: "80"
      activationLagThreshold: "20"
      offsetResetPolicy: latest
      allowIdleConsumers: "false"
      scaleToZeroOnInvalidOffset: "false"
      excludePersistentLag: "false"
      limitToPartitionsWithLag: "false"
      ensureEvenDistributionOfPartitions: "true"
