apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-api
  template:
    metadata:
      labels:
        app: notification-api
    spec:
      nodeSelector:
        worker: knight3007
      containers:
      - name: notification-api
        image: hoangdonguit/notification-service:latest
        command: ["/app/notification-api"]
        ports:
        - containerPort: 8084
        env:
        - name: APP_NAME
          value: "notification-service"
        - name: APP_PORT
          value: "8084"
        - name: APP_ENV
          value: "development"
        - name: DB_URL
          value: "postgres://postgres:securepassword@postgresql.db.svc.cluster.local:5432/notification_db?sslmode=disable"
        - name: KAFKA_BROKER
          value: "10.43.238.7:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-api
  namespace: default
spec:
  selector:
    app: notification-api
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-consumer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-consumer
  template:
    metadata:
      labels:
        app: notification-consumer
    spec:
      nodeSelector:
        worker: knight3007
      containers:
      - name: notification-consumer
        image: hoangdonguit/notification-service:latest
        command: ["/app/notification-consumer"]
        env:
        - name: APP_NAME
          value: "notification-service"
        - name: APP_PORT
          value: "8084"
        - name: APP_ENV
          value: "development"
        - name: DB_URL
          value: "postgres://postgres:securepassword@postgresql.db.svc.cluster.local:5432/notification_db?sslmode=disable"
        - name: KAFKA_BROKER
          value: "10.43.238.7:9092"
