apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-api
  template:
    metadata:
      labels:
        app: payment-api
    spec:
      containers:
      - name: payment-api
        image: hoangdonguit/payment-service:latest
        command: ["/app/payment-api"]
        ports:
        - containerPort: 8083
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        env:
        - name: APP_NAME
          value: "payment-service"
        - name: APP_PORT
          value: "8083"
        - name: APP_ENV
          value: "development"
        - name: DB_URL
          value: "postgres://postgres:securepassword@10.43.190.247:5432/payment_db?sslmode=disable"
        - name: KAFKA_BROKER
          value: "10.43.246.98:9092"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-consumer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-consumer
  template:
    metadata:
      labels:
        app: payment-consumer
    spec:
      containers:
      - name: payment-consumer
        image: hoangdonguit/payment-service:latest
        command: ["/app/payment-consumer"]
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        env:
        - name: APP_NAME
          value: "payment-service"
        - name: APP_PORT
          value: "8083"
        - name: APP_ENV
          value: "development"
        - name: DB_URL
          value: "postgres://postgres:securepassword@10.43.190.247:5432/payment_db?sslmode=disable"
        - name: KAFKA_BROKER
          value: "10.43.246.98:9092"