apiVersion: apps/v1
kind: Deployment
metadata:
  name: read-model-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: read-model-service
  template:
    metadata:
      labels:
        app: read-model-service
        sidecar.istio.io/inject: 'true'
        security-tier: internal-api
      annotations:
        sidecar.istio.io/inject: 'true'
        traffic.sidecar.istio.io/excludeOutboundPorts: 5432,6379,9092,27017,4317,4318
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
    spec:
      nodeSelector:
        kubernetes.io/hostname: vm2-mesh
      serviceAccountName: read-model-service-sa
      containers:
      - name: read-model-service
        image: hoangdonguit/read-model-service:otel-full-saga-20260603005334
        ports:
        - containerPort: 8085
        env:
        - name: APP_NAME
          value: read-model-service
        - name: APP_PORT
          value: '8085'
        - name: APP_ENV
          value: development
        - name: KAFKA_BROKER
          value: kafka-svc.kafka.svc.cluster.local:9092
        - name: KAFKA_GROUP_ID
          value: read-model-service-group
        - name: KAFKA_TOPIC_PAYMENT_COMPLETED
          value: payment.completed
        - name: MONGODB_HOST
          value: mongodb.default.svc.cluster.local:27017
        - name: MONGODB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_INITDB_ROOT_PASSWORD
        - name: MONGODB_AUTH_SOURCE
          value: admin
        - name: MONGODB_DATABASE
          value: ecommerce_read
        - name: MONGODB_COLLECTION
          value: order_read_models
        - name: OTEL_ENABLED
          value: 'true'
        - name: OTEL_SERVICE_NAME
          value: read-model-service
        - name: OTEL_ENVIRONMENT
          value: development
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: otel-collector.observability.svc.cluster.local:4317
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: read-model-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: read-model-service
  ports:
  - name: http
    port: 8085
    targetPort: 8085
    appProtocol: http
