apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-runtime-secrets
  namespace: default
type: Opaque
stringData:
  ORDER_DB_URL: "postgres://postgres:<POSTGRES_PASSWORD>@pgbouncer.db.svc.cluster.local:6432/order_db?sslmode=disable"
  INVENTORY_DB_URL: "postgres://postgres:<POSTGRES_PASSWORD>@pgbouncer.db.svc.cluster.local:6432/inventory_db?sslmode=disable"
  PAYMENT_DB_URL: "postgres://postgres:<POSTGRES_PASSWORD>@pgbouncer.db.svc.cluster.local:6432/payment_db?sslmode=disable"
  NOTIFICATION_DB_URL: "postgres://postgres:<POSTGRES_PASSWORD>@pgbouncer.db.svc.cluster.local:6432/notification_db?sslmode=disable"
  WEB_GATEWAY_API_KEY: "<WEB_GATEWAY_API_KEY>"
