apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-gateway-sa
  namespace: default
  labels:
    app.kubernetes.io/part-of: ecommerce-platform
    app.kubernetes.io/component: gateway

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-service-sa
  namespace: default
  labels:
    app.kubernetes.io/part-of: ecommerce-platform
    app.kubernetes.io/component: order

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-api-sa
  namespace: default
  labels:
    app.kubernetes.io/part-of: ecommerce-platform
    app.kubernetes.io/component: inventory-api

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-consumer-sa
  namespace: default
  labels:
    app.kubernetes.io/part-of: ecommerce-platform
    app.kubernetes.io/component: inventory-consumer

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-api-sa
  namespace: default
  labels:
    app.kubernetes.io/part-of: ecommerce-platform
    app.kubernetes.io/component: payment-api

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-consumer-sa
  namespace: default
  labels:
    app.kubernetes.io/part-of: ecommerce-platform
    app.kubernetes.io/component: payment-consumer

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-api-sa
  namespace: default
  labels:
    app.kubernetes.io/part-of: ecommerce-platform
    app.kubernetes.io/component: notification-api

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-consumer-sa
  namespace: default
  labels:
    app.kubernetes.io/part-of: ecommerce-platform
    app.kubernetes.io/component: notification-consumer

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: read-model-service-sa
  namespace: default
  labels:
    app.kubernetes.io/part-of: ecommerce-platform
    app.kubernetes.io/component: read-model
