apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-gateway
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-gateway
  template:
    metadata:
      labels:
        app: web-gateway
    spec:
      containers:
      - name: web-gateway
        image: hoangdonguit/web-gateway:latest
        ports:
        - containerPort: 8090
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        env:
        - name: APP_NAME
          value: "web-gateway"
        - name: APP_PORT
          value: "8090"
        - name: APP_ENV
          value: "development"
        - name: ORDER_SERVICE_URL
          value: "http://10.43.8.221:8081/api/v1"
        - name: INVENTORY_SERVICE_URL
          value: "http://10.43.39.73:8082/api/v1"
        - name: PAYMENT_SERVICE_URL
          value: "http://10.43.217.104:8083/api/v1"
        - name: NOTIFICATION_SERVICE_URL
          value: "http://10.43.56.172:8084/api/v1"