apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-gateway
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-gateway
  template:
    metadata:
      labels:
        app: web-gateway
    spec:
      containers:
      - name: web-gateway
        image: hoangdonguit/web-gateway:apikey-env-20260519160817
        ports:
        - containerPort: 8090
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        env:
        - name: APP_NAME
          value: "web-gateway"
        - name: APP_PORT
          value: "8090"
        - name: APP_ENV
          value: "development"
        - name: ORDER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: ecommerce-runtime-config
              key: ORDER_SERVICE_URL
        - name: INVENTORY_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: ecommerce-runtime-config
              key: INVENTORY_SERVICE_URL
        - name: PAYMENT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: ecommerce-runtime-config
              key: PAYMENT_SERVICE_URL
        - name: NOTIFICATION_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: ecommerce-runtime-config
              key: NOTIFICATION_SERVICE_URL
        - name: WEB_GATEWAY_API_KEY
          valueFrom:
            secretKeyRef:
              name: ecommerce-runtime-secrets
              key: WEB_GATEWAY_API_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: web-gateway
  namespace: default
spec:
  selector:
    app: web-gateway
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
